import Head from "next/head";
import type { AppProps } from "next/app";
import Layout from "../Layout";
import { useEffect } from "react";
import { Inter } from '@next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import "../styles/globals.css";

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <div className={inter.className}>
      <Head>
        <title>VPA App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </div>
  );
}
